import Head from "next/head";
import { Button } from "~/components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>WarungKu</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/warungku.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1>WarungKu</h1>
        <Button>Login</Button>
      </main>
    </>
  );
}
